ATTR_LIST = [
    "Accessible",
    "Active",
    "Adaptable",
    "Admirable",
    "Adventurous",
    "Agreeable",
    "Alert",
    "Allocentric",
    "Amiable",
    "Anticipative",
    "Appreciative",
    "Articulate",
    "Aspiring",
    "Athletic",
    "Attractive",
    "Balanced",
    "Benevolent",
    "Brilliant",
    "Calm",
    "Capable",
    "Captivating",
    "Caring",
    "Challenging",
    "Charismatic",
    "Charming",
    "Cheerful",
    "Clean",
    "Clear-headed",
    "Clever",
    "Colorful",
    "Companionly",
    "Compassionate",
    "Conciliatory",
    "Confident",
    "Conscientious",
    "Considerate",
    "Constant",
    "Contemplative",
    "Cooperative",
    "Courageous",
    "Courteous",
    "Creative",
    "Cultured",
    "Curious",
    "Daring",
    "Debonair",
    "Decent",
    "Decisive",
    "Dedicated",
    "Deep",
    "Dignified",
    "Directed",
    "Disciplined",
    "Discreet",
    "Dramatic",
    "Dutiful",
    "Dynamic",
    "Earnest",
    "Ebullient",
    "Educated",
    "Efficient",
    "Elegant",
    "Eloquent",
    "Empathetic",
    "Energetic",
    "Enthusiastic",
    "Esthetic",
    "Exciting",
    "Extraordinary",
    "Fair",
    "Faithful",
    "Farsighted",
    "Felicific",
    "Firm",
    "Flexible",
    "Focused",
    "Forceful",
    "Forgiving",
    "Forthright",
    "Freethinking",
    "Friendly",
    "Fun-loving",
    "Gallant",
    "Generous",
    "Gentle",
    "Genuine",
    "Good-natured",
    "Gracious",
    "Hardworking",
    "Healthy",
    "Hearty",
    "Helpful",
    "Heroic",
    "High-minded",
    "Honest",
    "Honorable",
    "Humble",
    "Humorous",
    "Idealistic",
    "Imaginative",
    "Impressive",
    "Incisive",
    "Incorruptible",
    "Independent",
    "Individualistic",
    "Innovative",
    "Inoffensive",
    "Insightful",
    "Insouciant",
    "Intelligent",
    "Intuitive",
    "Invulnerable",
    "Kind",
    "Knowledge",
    "Leaderly",
    "Leisurely",
    "Liberal",
    "Logical",
    "Lovable",
    "Loyal",
    "Lyrical",
    "Magnanimous",
    "Many-sided",
    "Masculine(Manly)",
    "Mature",
    "Methodical",
    "Meticulous",
    "Moderate",
    "Modest",
    "Multi-leveled",
    "Neat",
    "Nonauthoritarian",
    "Objective",
    "Observant",
    "Open",
    "Optimistic",
    "Orderly",
    "Organized",
    "Original",
    "Painstaking",
    "Passionate",
    "Patient",
    "Patriotic",
    "Peaceful",
    "Perceptive",
    "Perfectionist",
    "Personable",
    "Persuasive",
    "Planful",
    "Playful",
    "Polished",
    "Popular",
    "Practical",
    "Precise",
    "Principled",
    "Profound",
    "Protean",
    "Protective",
    "Providential",
    "Prudent",
    "Punctual",
    "Purposeful",
    "Rational",
    "Realistic",
    "Reflective",
    "Relaxed",
    "Reliable",
    "Resourceful",
    "Respectful",
    "Responsible",
    "Responsive",
    "Reverential",
    "Romantic",
    "Rustic",
    "Sage",
    "Sane",
    "Scholarly",
    "Scrupulous",
    "Secure",
    "Selfless",
    "Self-critical",
    "Self-defacing",
    "Self-denying",
    "Self-reliant",
    "Self-sufficient",
    "Sensitive",
    "Sentimental",
    "Seraphic",
    "Serious",
    "Sexy",
    "Sharing",
    "Shrewd",
    "Simple",
    "Skillful",
    "Sober",
    "Sociable",
    "Solid",
    "Sophisticated",
    "Spontaneous",
    "Sporting",
    "Stable",
    "Steadfast",
    "Steady",
    "Stoic",
    "Strong",
    "Studious",
    "Suave",
    "Subtle",
    "Sweet",
    "Sympathetic",
    "Systematic",
    "Tasteful",
    "Teacherly",
    "Thorough",
    "Tidy",
    "Tolerant",
    "Tractable",
    "Trusting",
    "Uncomplaining",
    "Understanding",
    "Undogmatic",
    "Unfoolable",
    "Upright",
    "Urbane",
    "Venturesome",
    "Vivacious",
    "Warm",
    "Well-bred",
    "Well-read",
    "Well-rounded",
    "Winning",
    "Wise",
    "Witty",
    "Youthful",
    "Absentminded",
    "Aggressive",
    "Ambitious",
    "Amusing",
    "Artful",
    "Ascetic",
    "Authoritarian",
    "Big-thinking",
    "Boyish",
    "Breezy",
    "Businesslike",
    "Busy",
    "Casual",
    "Cerebral",
    "Chummy",
    "Circumspect",
    "Competitive",
    "Complex",
    "Confidential",
    "Conservative",
    "Contradictory",
    "Crisp",
    "Cute",
    "Deceptive",
    "Determined",
    "Dominating",
    "Dreamy",
    "Driving",
    "Droll",
    "Dry",
    "Earthy",
    "Effeminate",
    "Emotional",
    "Enigmatic",
    "Experimental",
    "Familial",
    "Folksy",
    "Formal",
    "Freewheeling",
    "Frugal",
    "Glamorous",
    "Guileless",
    "High-spirited",
    "Hurried",
    "Hypnotic",
    "Iconoclastic",
    "Idiosyncratic",
    "Impassive",
    "Impersonal",
    "Impressionable",
    "Intense",
    "Invisible",
    "Irreligious",
    "Irreverent",
    "Maternal",
    "Mellow",
    "Modern",
    "Moralistic",
    "Mystical",
    "Neutral",
    "Noncommittal",
    "Noncompetitive",
    "Obedient",
    "Old-fashioned",
    "Ordinary",
    "Outspoken",
    "Paternalistic",
    "Physical",
    "Placid",
    "Political",
    "Predictable",
    "Preoccupied",
    "Private",
    "Progressive",
    "Proud",
    "Pure",
    "Questioning",
    "Quiet",
    "Religious",
    "Reserved",
    "Restrained",
    "Retiring",
    "Sarcastic",
    "Self-conscious",
    "Sensual",
    "Skeptical",
    "Smooth",
    "Soft",
    "Solemn",
    "Solitary",
    "Stern",
    "Stolid",
    "Strict",
    "Stubborn",
    "Stylish",
    "Subjective",
    "Surprising",
    "Soft",
    "Tough",
    "Unaggressive",
    "Unambitious",
    "Unceremonious",
    "Unchanging",
    "Undemanding",
    "Unfathomable",
    "Unhurried",
    "Uninhibited",
    "Unpatriotic",
    "Unpredictable",
    "Unreligious",
    "Unsentimental",
    "Whimsical",
    "Abrasive",
    "Abrupt",
    "Agonizing",
    "Aimless",
    "Airy",
    "Aloof",
    "Amoral",
    "Angry",
    "Anxious",
    "Apathetic",
    "Arbitrary",
    "Argumentative",
    "Arrogant",
    "Artificial",
    "Asocial",
    "Assertive",
    "Astigmatic",
    "Barbaric",
    "Bewildered",
    "Bizarre",
    "Bland",
    "Blunt",
    "Biosterous",
    "Brittle",
    "Brutal",
    "Calculating",
    "Callous",
    "Cantakerous",
    "Careless",
    "Cautious",
    "Charmless",
    "Childish",
    "Clumsy",
    "Coarse",
    "Cold",
    "Colorless",
    "Complacent",
    "Complaintive",
    "Compulsive",
    "Conceited",
    "Condemnatory",
    "Conformist",
    "Confused",
    "Contemptible",
    "Conventional",
    "Cowardly",
    "Crafty",
    "Crass",
    "Crazy",
    "Criminal",
    "Critical",
    "Crude",
    "Cruel",
    "Cynical",
    "Decadent",
    "Deceitful",
    "Delicate",
    "Demanding",
    "Dependent",
    "Desperate",
    "Destructive",
    "Devious",
    "Difficult",
    "Dirty",
    "Disconcerting",
    "Discontented",
    "Discouraging",
    "Discourteous",
    "Dishonest",
    "Disloyal",
    "Disobedient",
    "Disorderly",
    "Disorganized",
    "Disputatious",
    "Disrespectful",
    "Disruptive",
    "Dissolute",
    "Dissonant",
    "Distractible",
    "Disturbing",
    "Dogmatic",
    "Domineering",
    "Dull",
    "EasilyDiscouraged",
    "Egocentric",
    "Enervated",
    "Envious",
    "Erratic",
    "Escapist",
    "Excitable",
    "Expedient",
    "Extravagant",
    "Extreme",
    "Faithless",
    "False",
    "Fanatical",
    "Fanciful",
    "Fatalistic",
    "Fawning",
    "Fearful",
    "Fickle",
    "Fiery",
    "Fixed",
    "Flamboyant",
    "Foolish",
    "Forgetful",
    "Fraudulent",
    "Frightening",
    "Frivolous",
    "Gloomy",
    "Graceless",
    "Grand",
    "Greedy",
    "Grim",
    "Gullible",
    "Hateful",
    "Haughty",
    "Hedonistic",
    "Hesitant",
    "Hidebound",
    "High-handed",
    "Hostile",
    "Ignorant",
    "Imitative",
    "Impatient",
    "Impractical",
    "Imprudent",
    "Impulsive",
    "Inconsiderate",
    "Incurious",
    "Indecisive",
    "Indulgent",
    "Inert",
    "Inhibited",
    "Insecure",
    "Insensitive",
    "Insincere",
    "Insulting",
    "Intolerant",
    "Irascible",
    "Irrational",
    "Irresponsible",
    "Irritable",
    "Lazy",
    "Libidinous",
    "Loquacious",
    "Malicious",
    "Mannered",
    "Mannerless",
    "Mawkish",
    "Mealymouthed",
    "Mechanical",
    "Meddlesome",
    "Melancholic",
    "Meretricious",
    "Messy",
    "Miserable",
    "Miserly",
    "Misguided",
    "Mistaken",
    "Money-minded",
    "Monstrous",
    "Moody",
    "Morbid",
    "Muddle-headed",
    "Naive",
    "Narcissistic",
    "Narrow",
    "Narrow-minded",
    "Natty",
    "Negativistic",
    "Neglectful",
    "Neurotic",
    "Nihilistic",
    "Obnoxious",
    "Obsessive",
    "Obvious",
    "Odd",
    "Offhand",
    "One-dimensional",
    "One-sided",
    "Opinionated",
    "Opportunistic",
    "Oppressed",
    "Outrageous",
    "Overimaginative",
    "Paranoid",
    "Passive",
    "Pedantic",
    "Perverse",
    "Petty",
    "Pharissical",
    "Phlegmatic",
    "Plodding",
    "Pompous",
    "Possessive",
    "Power-hungry",
    "Predatory",
    "Prejudiced",
    "Presumptuous",
    "Pretentious",
    "Prim",
    "Procrastinating",
    "Profligate",
    "Provocative",
    "Pugnacious",
    "Puritanical",
    "Quirky",
    "Reactionary",
    "Reactive",
    "Regimental",
    "Regretful",
    "Repentant",
    "Repressed",
    "Resentful",
    "Ridiculous",
    "Rigid",
    "Ritualistic",
    "Rowdy",
    "Ruined",
    "Sadistic",
    "Sanctimonious",
    "Scheming",
    "Scornful",
    "Secretive",
    "Sedentary",
    "Selfish",
    "Self-indulgent",
    "Shallow",
    "Shortsighted",
    "Shy",
    "Silly",
    "Single-minded",
    "Sloppy",
    "Slow",
    "Sly",
    "Small-thinking",
    "Softheaded",
    "Sordid",
    "Steely",
    "Stiff",
    "Strong-willed",
    "Stupid",
    "Submissive",
    "Superficial",
    "Superstitious",
    "Suspicious",
    "Tactless",
    "Tasteless",
    "Tense",
    "Thievish",
    "Thoughtless",
    "Timid",
    "Transparent",
    "Treacherous",
    "Trendy",
    "Troublesome",
    "Unappreciative",
    "Uncaring",
    "Uncharitable",
    "Unconvincing",
    "Uncooperative",
    "Uncreative",
    "Uncritical",
    "Unctuous",
    "Undisciplined",
    "Unfriendly",
    "Ungrateful",
    "Unhealthy",
    "Unimaginative",
    "Unimpressive",
    "Unlovable",
    "Unpolished",
    "Unprincipled",
    "Unrealistic",
    "Unreflective",
    "Unreliable",
    "Unrestrained",
    "Unself-critical",
    "Unstable",
    "Vacuous",
    "Vague",
    "Venal",
    "Venomous",
    "Vindictive",
    "Vulnerable",
    "Weak",
    "Weak-willed",
    "Well-meaning",
    "Willful",
    "Wishful",
    "Zany"
]

POT_DICT_LIST = [
    {
        "appearance": "thin, light-blue liquid that shrinks and retracts in a steady rhythm.",
        "taste": "tastes of bitterly cooked seeds and causes one's tongue to shrink."
    },
    {
        "appearance": "swirling violet sheen.",
        "taste": "tastes of wax and causes one to hear, only just, a slight cacophony of voices."
    },
    {
        "appearance": "misty gray that evaporates and returns to liquid every once in a while.",
        "taste": "tastes of cool air and causes one's tongue to turn to a near gas-like state."
    },
    {
        "appearance": "thick green that seems to expand and return to its original size",
        "taste": "tastes of watermelon and causes one's tongue to surge in size."
    },
    {
        "appearance": "viscous red that appears like blood.",
        "taste": "tastes of licorice and causes any scarring or pitting in the mouth to smooth over."
    },
    {
        "appearance": "clear liquid that refracts light.",
        "taste": "tastes of lamp oil and causes one's tongue and teeth to briefly disappear."
    },
    {
        "appearance": "fine cerulean liquid that seems to suspend itself within the vial.",
        "taste": "tastes of blueberries and causes one's tongue to lift to the top of one's mouth."
    },
    {
        "appearance": "brown sticky liquid.",
        "taste": "tastes of...glue..."
    },
    {
        "appearance": "swirling gaseous brown sticky liquid.",
        "taste": "tastes of...glue...with a hint of wind?"
    },

    {
        "appearance": "deep blue rotating against its own reflection.",
        "taste": "tastes of bitter hemlock and causes one's tongue to numb."
    }
]
POT_COUNT = len(POT_DICT_LIST)

CLASS_LIST = [
    "Thief",
    "Fighter",
    "Cleric",
    "Dwarf",
    "Halfling",
    "Elf",
    "Magic User",
    "Alchemist",
    "Illusionist",
    "Gnome",
    "Gargantua",
    "Warden",
    "Ranger",
    "Assassin",
    "Acrobat",
    "Beast Master",
    "Goblin",
    "Necromancer",
    "Druid",
    "Merchant",
    "Archer",
]
CLASS_LIST_LENGTH = len(CLASS_LIST)

MASTER_SPELL_DICT = {
    "MAGIC-USER": {
        "1": [
            "Charm Person",
            "Detect Magic",
            "Floating Disc",
            "Hold Portal",
            "Light(Darkness)",
            "Magic Missile",
            "Protection from Evil",
            "Read Languages",
            "Read Magic",
            "Shield",
            "Sleep",
            "Ventriloquism"
        ],
        "2": [
            "Continual Light (Continual Darkness)",
            "Detect Evil",
            "Detect Invisible",
            "ESP",
            "Invisibility",
            "Knock",
            "Levitate",
            "Locate Object",
            "Mirror Image",
            "Phantasmal Force",
            "Web",
            "Wizard Lock"
        ],
        "3": [
            "Clairvoyance",
            "Dispel Magic",
            "Fire Ball",
            "Fly",
            "Haste",
            "Hold Person",
            "Infravision",
            "Invisibility 10’ Radius",
            "Lightning Bolt",
            "Protection from Evil 10’ Radius",
            "Protection from Normal Missiles",
            "Water Breathing"
        ],
        "4": [
            "Charm Monster",
            "Confusion",
            "Dimension Door",
            "Growth of Plants",
            "Hallucinatory Terrain",
            "Massmorph",
            "Polymorph Others",
            "Polymorph Self",
            "Remove Curse (Curse)",
            "Wall of Fire",
            "Wall of Ice",
            "Wizard Eye"
        ],
        "5": [
            "Animate Dead",
            "Cloudkill",
            "Conjure Elemental",
            "Contact Higher Plane",
            "Feeblemind",
            "Hold Monster",
            "Magic Jar",
            "Pass-Wall",
            "Telekinesis",
            "Teleport",
            "Transmute Rock to Mud (Mud to Rock)",
            "Wall of Stone"
        ],
        "6": [
            "Anti-Magic Shell",
            "Control Weather",
            "Death Spell",
            "Disintegrate",
            "Geas (Remove Geas)",
            "Invisible Stalker",
            "Lower Water",
            "Move Earth",
            "Part Water",
            "Projected Image",
            "Reincarnation",
            "Stone to Flesh (Flesh to Stone)"
        ],
    },
    "CLERIC": {
        "1": {
            "Cure Light Wounds (Cause Lt. Wounds)",
            "Detect Evil",
            "Detect Magic",
            "Light (Darkness)",
            "Protection from Evil",
            "Purify Food and Water",
            "Remove Fear (Cause Fear)",
            "Resist Cold"
        },
        "2": {
            "Bless (Blight)",
            "Find Traps",
            "Hold Person",
            "Know Alignment",
            "Resist Fire",
            "Silence 15’ Radius",
            "Snake Charm",
            "Speak with Animals"
        },
        "3": {
            "Continual Light (Continual Darkness)",
            "Cure Disease (Cause Disease)",
            "Growth of Animal",
            "Locate Object",
            "Remove Curse (Curse)",
            "Striking"
        },
        "4": {
            "Create Water",
            "Cure Serious Wounds (Cause Sr. Wounds)",
            "Neutralize Poison",
            "Protection from Evil 10’ Radius",
            "Speak with Plants",
            "Sticks to Snakes"
        },
        "5": {
            "Commune",
            "Create Food",
            "Dispel Evil",
            "Insect Plague",
            "Quest (Remove Quest)",
            "Raise Dead (Finger of Death)"
        },
    },
    "DRUID": {
        "1": {
            "Animal Friendship",
            "Detect Danger",
            "Entangle",
            "Faerie Fire",
            "Invisibility to Animals",
            "Locate Plant or Animal",
            "Moon Touched",
            "Phantom Shield",
            "Predict Weather",
            "Speak with Animals"
        },
        "2": {
            "Barkskin",
            "Create Water",
            "Cure Light Wounds (Cause Light Wounds)",
            "Heat Metal",
            "Night's Companion",
            "Obscuring Mist",
            "Poisonous Stare",
            "Produce Flame",
            "Slow Poison",
            "Warp Wood"
        },
        "3": {
            "Black Lightning",
            "Body of Eyes",
            "Call Lightning",
            "Growth of Nature",
            "Hold Animal",
            "Protection from Poison",
            "Starlight",
            "Summon Winged Steed",
            "Tree Shape",
            "Water Breathing (Air Breathing)"
        },
        "4": {
            "Cure Serious Wounds (Cause Serious Wounds)",
            "Dispel Magic",
            "Incantation of the Moon",
            "Poisonous Spittle",
            "Protection from Fire and Lightning",
            "Speak with Plants",
            "Starlight Form",
            "Summon Animals",
            "Temperature Control"
        },
        "5": {
            "Breathe Fire",
            "Commune with Nature",
            "Control Weather",
            "Maelstrom",
            "Pass Plant",
            "Protection from Plants and Animals",
            "Transmute Rock to Mud (Mud to Rock)",
            "Wall of Thorns"
        }
    },
    "ILLUSIONIST": {
        "1": {
            "Auditory Illusion",
            "Chromatic Orb",
            "Color Spray",
            "Dancing Lights",
            "Detect Illusion",
            "Glamour",
            "Hideous Laughter",
            "Hypnotism",
            "Light (Darkness)",
            "Phantasmal Force",
            "Phantom Shield",
            "Read Magic",
            "Spook",
            "Synesthesia",
            "Wall of Fog"
        },
        "2": {
            "Alter Self",
            "Blindness / Deafness",
            "Blur",
            "Detect Magic",
            "Discord",
            "False Aura",
            "Fascinate",
            "Hypnotic Pattern",
            "Improved Phantasmal Force",
            "Invisibility",
            "Magic Mouth",
            "Mirror Image",
            "Phantasmal Armor",
            "Quasimorph",
            "Whispering Wind"
        },
        "3": {
            "Blacklight",
            "Cackling Skull",
            "Dispel Illusion",
            "Fear",
            "Hallucinatory Terrain",
            "Invisibility 10’ Radius",
            "Nondetection",
            "Paralysation",
            "Phantom Steed",
            "Rope Trick",
            "Sensory Overload",
            "Spectral Force",
            "Suggestion",
            "Wraithform"
        },
        "4": {
            "Chimerical Force",
            "Confusion",
            "Dispel Magic",
            "Emotion",
            "Illusory Stamina",
            "Improved Invisibility",
            "Massmorph",
            "Minor Creation",
            "Phantasmal Killer",
            "Rainbow Pattern",
            "Shadow Monsters",
            "Solid Fog",
            "Veil of Abandonment"
        },
        "5": {
            "Chaos",
            "Demi-Shadow Monsters",
            "Illusion",
            "Looking Glass",
            "Major Creation",
            "Maze of Mirrors",
            "Mind Fog",
            "Phantasmagoria",
            "Projected Image",
            "Seeming",
            "Shadowcast",
            "Shadowy Transformation",
            "Spell Storing",
            "Time Flow",
            "Visitation"
        },
        "6": {
            "Acid Fog",
            "Dream Quest",
            "Impersonation",
            "Manifest Dream",
            "Mass Suggestion",
            "Mislead",
            "Permanent Illusion",
            "Shades",
            "Through the Looking Glass",
            "Triggered Illusion",
            "True Seeing",
            "Vision"
        },
    },
    "NECROMANCER": {
        "1": {
            "Chill Touch",
            "Command Dead",
            "Corpse Visage",
            "Decay",
            "Deathlight",
            "Detect Undead",
            "Marionette",
            "Pass Undead",
            "Protection from Evil",
            "REad MAgic",
            "Skull Speech",
            "Undead Servitor"
        },
        "2": {
            "Bone Armor",
            "Choke",
            "Death Recall",
            "Detect Magic",
            "Feign Death",
            "Paralyzing Touch",
            "Seal Tomb",
            "Skeletal Steed",
            "Skull Sight",
            "Silence 15' Radius",
            "Speak with Dead",
            "Spectral Hand"
        },
        "3": {
            "Animate Dead, Temporary",
            "Bone Staff",
            "Carrion Stench",
            "Crypt Sight",
            "Death Ward",
            "Drag from Death's Door",
            "Fear",
            "Grave Breath",
            "Hold Person",
            "Protection from Evil 10' Radius",
            "Skull Trap",
            "Vampiric Touch"
        },
        "4": {
            "Command Undead",
            "Corpse Clairvoyance",
            "Corpse Mask",
            "Curse",
            "Dispel Magic",
            "Inter",
            "Rotting Touch",
            "Reassemble",
            "Skeletal Wings",
            "Swarm Transformation",
            "Wall of Bones",
            "Wound Transference"
        },
        "5": {
            "Animate Dead",
            "Bonewrack",
            "Cloudkill",
            "Commune with Spirit",
            "Gaseous Form",
            "Guardian Spirit",
            "Hold Undead",
            "Magic Jar",
            "Spirit Vision",
            "Summon Undead",
            "Veil of Life",
            "Wall of Gloom"
        },
        "6": {
            "Bonesteel",
            "Deathlessness",
            "Death Spell",
            "Doomveil",
            "Energy Drain",
            "Eternal Quest",
            "Necrotic Gaze",
            "Protection from Undead",
            "Sacrificial Resurrection",
            "Skeletal Army",
            "Spirit Shield",
            "Undead Regeneration"
        }
    }
}

BRAHMEL_SAYS_LIST_EXCLAIM = [
    "Aha! ",
    "Glorious! ",
    "Wonderful! ",
    "Truly exquisite! ",
    "Blessed be my ever-expanding mind! ",
    "Oh Brahmel, you've done it again! ",
]

BRAHMEL_SAYS_LIST_STATE = [
    "I've crafted a potion! ",
    "Another masterpiece! ",
    "I've created a tincture fit for kings! ",
    "Another concoction for the record books! ",
    "I've done it again! ",
    "Dr. Lumos is sure to fund such a serum! "
]