ATTR_LIST = [
    "Accessible",
    "Active",
    "Adaptable",
    "Admirable",
    "Adventurous",
    "Agreeable",
    "Alert",
    "Allocentric",
    "Amiable",
    "Anticipative",
    "Appreciative",
    "Articulate",
    "Aspiring",
    "Athletic",
    "Attractive",
    "Balanced",
    "Benevolent",
    "Brilliant",
    "Calm",
    "Capable",
    "Captivating",
    "Caring",
    "Challenging",
    "Charismatic",
    "Charming",
    "Cheerful",
    "Clean",
    "Clear-headed",
    "Clever",
    "Colorful",
    "Companionly",
    "Compassionate",
    "Conciliatory",
    "Confident",
    "Conscientious",
    "Considerate",
    "Constant",
    "Contemplative",
    "Cooperative",
    "Courageous",
    "Courteous",
    "Creative",
    "Cultured",
    "Curious",
    "Daring",
    "Debonair",
    "Decent",
    "Decisive",
    "Dedicated",
    "Deep",
    "Dignified",
    "Directed",
    "Disciplined",
    "Discreet",
    "Dramatic",
    "Dutiful",
    "Dynamic",
    "Earnest",
    "Ebullient",
    "Educated",
    "Efficient",
    "Elegant",
    "Eloquent",
    "Empathetic",
    "Energetic",
    "Enthusiastic",
    "Esthetic",
    "Exciting",
    "Extraordinary",
    "Fair",
    "Faithful",
    "Farsighted",
    "Felicific",
    "Firm",
    "Flexible",
    "Focused",
    "Forceful",
    "Forgiving",
    "Forthright",
    "Freethinking",
    "Friendly",
    "Fun-loving",
    "Gallant",
    "Generous",
    "Gentle",
    "Genuine",
    "Good-natured",
    "Gracious",
    "Hardworking",
    "Healthy",
    "Hearty",
    "Helpful",
    "Heroic",
    "High-minded",
    "Honest",
    "Honorable",
    "Humble",
    "Humorous",
    "Idealistic",
    "Imaginative",
    "Impressive",
    "Incisive",
    "Incorruptible",
    "Independent",
    "Individualistic",
    "Innovative",
    "Inoffensive",
    "Insightful",
    "Insouciant",
    "Intelligent",
    "Intuitive",
    "Invulnerable",
    "Kind",
    "Knowledge",
    "Leaderly",
    "Leisurely",
    "Liberal",
    "Logical",
    "Lovable",
    "Loyal",
    "Lyrical",
    "Magnanimous",
    "Many-sided",
    "Masculine(Manly)",
    "Mature",
    "Methodical",
    "Meticulous",
    "Moderate",
    "Modest",
    "Multi-leveled",
    "Neat",
    "Nonauthoritarian",
    "Objective",
    "Observant",
    "Open",
    "Optimistic",
    "Orderly",
    "Organized",
    "Original",
    "Painstaking",
    "Passionate",
    "Patient",
    "Patriotic",
    "Peaceful",
    "Perceptive",
    "Perfectionist",
    "Personable",
    "Persuasive",
    "Planful",
    "Playful",
    "Polished",
    "Popular",
    "Practical",
    "Precise",
    "Principled",
    "Profound",
    "Protean",
    "Protective",
    "Providential",
    "Prudent",
    "Punctual",
    "Purposeful",
    "Rational",
    "Realistic",
    "Reflective",
    "Relaxed",
    "Reliable",
    "Resourceful",
    "Respectful",
    "Responsible",
    "Responsive",
    "Reverential",
    "Romantic",
    "Rustic",
    "Sage",
    "Sane",
    "Scholarly",
    "Scrupulous",
    "Secure",
    "Selfless",
    "Self-critical",
    "Self-defacing",
    "Self-denying",
    "Self-reliant",
    "Self-sufficient",
    "Sensitive",
    "Sentimental",
    "Seraphic",
    "Serious",
    "Sexy",
    "Sharing",
    "Shrewd",
    "Simple",
    "Skillful",
    "Sober",
    "Sociable",
    "Solid",
    "Sophisticated",
    "Spontaneous",
    "Sporting",
    "Stable",
    "Steadfast",
    "Steady",
    "Stoic",
    "Strong",
    "Studious",
    "Suave",
    "Subtle",
    "Sweet",
    "Sympathetic",
    "Systematic",
    "Tasteful",
    "Teacherly",
    "Thorough",
    "Tidy",
    "Tolerant",
    "Tractable",
    "Trusting",
    "Uncomplaining",
    "Understanding",
    "Undogmatic",
    "Unfoolable",
    "Upright",
    "Urbane",
    "Venturesome",
    "Vivacious",
    "Warm",
    "Well-bred",
    "Well-read",
    "Well-rounded",
    "Winning",
    "Wise",
    "Witty",
    "Youthful",
    "Absentminded",
    "Aggressive",
    "Ambitious",
    "Amusing",
    "Artful",
    "Ascetic",
    "Authoritarian",
    "Big-thinking",
    "Boyish",
    "Breezy",
    "Businesslike",
    "Busy",
    "Casual",
    "Cerebral",
    "Chummy",
    "Circumspect",
    "Competitive",
    "Complex",
    "Confidential",
    "Conservative",
    "Contradictory",
    "Crisp",
    "Cute",
    "Deceptive",
    "Determined",
    "Dominating",
    "Dreamy",
    "Driving",
    "Droll",
    "Dry",
    "Earthy",
    "Effeminate",
    "Emotional",
    "Enigmatic",
    "Experimental",
    "Familial",
    "Folksy",
    "Formal",
    "Freewheeling",
    "Frugal",
    "Glamorous",
    "Guileless",
    "High-spirited",
    "Hurried",
    "Hypnotic",
    "Iconoclastic",
    "Idiosyncratic",
    "Impassive",
    "Impersonal",
    "Impressionable",
    "Intense",
    "Invisible",
    "Irreligious",
    "Irreverent",
    "Maternal",
    "Mellow",
    "Modern",
    "Moralistic",
    "Mystical",
    "Neutral",
    "Noncommittal",
    "Noncompetitive",
    "Obedient",
    "Old-fashioned",
    "Ordinary",
    "Outspoken",
    "Paternalistic",
    "Physical",
    "Placid",
    "Political",
    "Predictable",
    "Preoccupied",
    "Private",
    "Progressive",
    "Proud",
    "Pure",
    "Questioning",
    "Quiet",
    "Religious",
    "Reserved",
    "Restrained",
    "Retiring",
    "Sarcastic",
    "Self-conscious",
    "Sensual",
    "Skeptical",
    "Smooth",
    "Soft",
    "Solemn",
    "Solitary",
    "Stern",
    "Stolid",
    "Strict",
    "Stubborn",
    "Stylish",
    "Subjective",
    "Surprising",
    "Soft",
    "Tough",
    "Unaggressive",
    "Unambitious",
    "Unceremonious",
    "Unchanging",
    "Undemanding",
    "Unfathomable",
    "Unhurried",
    "Uninhibited",
    "Unpatriotic",
    "Unpredictable",
    "Unreligious",
    "Unsentimental",
    "Whimsical",
    "Abrasive",
    "Abrupt",
    "Agonizing",
    "Aimless",
    "Airy",
    "Aloof",
    "Amoral",
    "Angry",
    "Anxious",
    "Apathetic",
    "Arbitrary",
    "Argumentative",
    "Arrogant",
    "Artificial",
    "Asocial",
    "Assertive",
    "Astigmatic",
    "Barbaric",
    "Bewildered",
    "Bizarre",
    "Bland",
    "Blunt",
    "Biosterous",
    "Brittle",
    "Brutal",
    "Calculating",
    "Callous",
    "Cantakerous",
    "Careless",
    "Cautious",
    "Charmless",
    "Childish",
    "Clumsy",
    "Coarse",
    "Cold",
    "Colorless",
    "Complacent",
    "Complaintive",
    "Compulsive",
    "Conceited",
    "Condemnatory",
    "Conformist",
    "Confused",
    "Contemptible",
    "Conventional",
    "Cowardly",
    "Crafty",
    "Crass",
    "Crazy",
    "Criminal",
    "Critical",
    "Crude",
    "Cruel",
    "Cynical",
    "Decadent",
    "Deceitful",
    "Delicate",
    "Demanding",
    "Dependent",
    "Desperate",
    "Destructive",
    "Devious",
    "Difficult",
    "Dirty",
    "Disconcerting",
    "Discontented",
    "Discouraging",
    "Discourteous",
    "Dishonest",
    "Disloyal",
    "Disobedient",
    "Disorderly",
    "Disorganized",
    "Disputatious",
    "Disrespectful",
    "Disruptive",
    "Dissolute",
    "Dissonant",
    "Distractible",
    "Disturbing",
    "Dogmatic",
    "Domineering",
    "Dull",
    "EasilyDiscouraged",
    "Egocentric",
    "Enervated",
    "Envious",
    "Erratic",
    "Escapist",
    "Excitable",
    "Expedient",
    "Extravagant",
    "Extreme",
    "Faithless",
    "False",
    "Fanatical",
    "Fanciful",
    "Fatalistic",
    "Fawning",
    "Fearful",
    "Fickle",
    "Fiery",
    "Fixed",
    "Flamboyant",
    "Foolish",
    "Forgetful",
    "Fraudulent",
    "Frightening",
    "Frivolous",
    "Gloomy",
    "Graceless",
    "Grand",
    "Greedy",
    "Grim",
    "Gullible",
    "Hateful",
    "Haughty",
    "Hedonistic",
    "Hesitant",
    "Hidebound",
    "High-handed",
    "Hostile",
    "Ignorant",
    "Imitative",
    "Impatient",
    "Impractical",
    "Imprudent",
    "Impulsive",
    "Inconsiderate",
    "Incurious",
    "Indecisive",
    "Indulgent",
    "Inert",
    "Inhibited",
    "Insecure",
    "Insensitive",
    "Insincere",
    "Insulting",
    "Intolerant",
    "Irascible",
    "Irrational",
    "Irresponsible",
    "Irritable",
    "Lazy",
    "Libidinous",
    "Loquacious",
    "Malicious",
    "Mannered",
    "Mannerless",
    "Mawkish",
    "Mealymouthed",
    "Mechanical",
    "Meddlesome",
    "Melancholic",
    "Meretricious",
    "Messy",
    "Miserable",
    "Miserly",
    "Misguided",
    "Mistaken",
    "Money-minded",
    "Monstrous",
    "Moody",
    "Morbid",
    "Muddle-headed",
    "Naive",
    "Narcissistic",
    "Narrow",
    "Narrow-minded",
    "Natty",
    "Negativistic",
    "Neglectful",
    "Neurotic",
    "Nihilistic",
    "Obnoxious",
    "Obsessive",
    "Obvious",
    "Odd",
    "Offhand",
    "One-dimensional",
    "One-sided",
    "Opinionated",
    "Opportunistic",
    "Oppressed",
    "Outrageous",
    "Overimaginative",
    "Paranoid",
    "Passive",
    "Pedantic",
    "Perverse",
    "Petty",
    "Pharissical",
    "Phlegmatic",
    "Plodding",
    "Pompous",
    "Possessive",
    "Power-hungry",
    "Predatory",
    "Prejudiced",
    "Presumptuous",
    "Pretentious",
    "Prim",
    "Procrastinating",
    "Profligate",
    "Provocative",
    "Pugnacious",
    "Puritanical",
    "Quirky",
    "Reactionary",
    "Reactive",
    "Regimental",
    "Regretful",
    "Repentant",
    "Repressed",
    "Resentful",
    "Ridiculous",
    "Rigid",
    "Ritualistic",
    "Rowdy",
    "Ruined",
    "Sadistic",
    "Sanctimonious",
    "Scheming",
    "Scornful",
    "Secretive",
    "Sedentary",
    "Selfish",
    "Self-indulgent",
    "Shallow",
    "Shortsighted",
    "Shy",
    "Silly",
    "Single-minded",
    "Sloppy",
    "Slow",
    "Sly",
    "Small-thinking",
    "Softheaded",
    "Sordid",
    "Steely",
    "Stiff",
    "Strong-willed",
    "Stupid",
    "Submissive",
    "Superficial",
    "Superstitious",
    "Suspicious",
    "Tactless",
    "Tasteless",
    "Tense",
    "Thievish",
    "Thoughtless",
    "Timid",
    "Transparent",
    "Treacherous",
    "Trendy",
    "Troublesome",
    "Unappreciative",
    "Uncaring",
    "Uncharitable",
    "Unconvincing",
    "Uncooperative",
    "Uncreative",
    "Uncritical",
    "Unctuous",
    "Undisciplined",
    "Unfriendly",
    "Ungrateful",
    "Unhealthy",
    "Unimaginative",
    "Unimpressive",
    "Unlovable",
    "Unpolished",
    "Unprincipled",
    "Unrealistic",
    "Unreflective",
    "Unreliable",
    "Unrestrained",
    "Unself-critical",
    "Unstable",
    "Vacuous",
    "Vague",
    "Venal",
    "Venomous",
    "Vindictive",
    "Vulnerable",
    "Weak",
    "Weak-willed",
    "Well-meaning",
    "Willful",
    "Wishful",
    "Zany"
]

POT_DICT_LIST = [
    {
        "appearance": "thin, light-blue liquid that shrinks and retracts in a steady rhythm.",
        "taste": "tastes of bitterly cooked seeds and causes one's tongue to shrink."
    },
    {
        "appearance": "swirling violet sheen.",
        "taste": "tastes of wax and causes one to hear, only just, a slight cacophony of voices."
    },
    {
        "appearance": "misty gray that evaporates and returns to liquid every once in a while.",
        "taste": "tastes of cool air and causes one's tongue to turn to a near gas-like state."
    },
    {
        "appearance": "thick green that seems to expand and return to its original size",
        "taste": "tastes of watermelon and causes one's tongue to surge in size."
    },
    {
        "appearance": "viscous red that appears like blood.",
        "taste": "tastes of licorice and causes any scarring or pitting in the mouth to smooth over."
    },
    {
        "appearance": "clear liquid that refracts light.",
        "taste": "tastes of lamp oil and causes one's tongue and teeth to briefly disappear."
    },
    {
        "appearance": "fine cerulean liquid that seems to suspend itself within the vial.",
        "taste": "tastes of blueberries and causes one's tongue to lift to the top of one's mouth."
    },
    {
        "appearance": "brown sticky liquid.",
        "taste": "tastes of...glue..."
    },
    {
        "appearance": "swirling gaseous brown sticky liquid.",
        "taste": "tastes of...glue...with a hint of wind?"
    },

    {
        "appearance": "deep blue rotating against its own reflection.",
        "taste": "tastes of bitter hemlock and causes one's tongue to numb."
    },

    {
        "appearance": "velvety, violet sludge that fades between clear and opaque.",
        "taste": "tastes of elderberries and medicinal herbs."
    }
]
POT_COUNT = len(POT_DICT_LIST)

CLASS_LIST = [
    "Thief",
    "Fighter",
    "Cleric",
    "Dwarf",
    "Halfling",
    "Elf",
    "Magic User",
    "Alchemist",
    "Illusionist",
    "Gnome",
    "Gargantua",
    "Warden",
    "Ranger",
    "Assassin",
    "Acrobat",
    "Beast Master",
    "Goblin",
    "Necromancer",
    "Druid",
    "Merchant",
    "Archer",
]
CLASS_LIST_LENGTH = len(CLASS_LIST)

MASTER_SPELL_DICT = {
    "MAGIC-USER": {
        "1": [
            "Charm Person",
            "Detect Magic",
            "Floating Disc",
            "Hold Portal",
            "Light(Darkness)",
            "Magic Missile",
            "Protection from Evil",
            "Read Languages",
            "Read Magic",
            "Shield",
            "Sleep",
            "Ventriloquism"
        ],
        "2": [
            "Continual Light (Continual Darkness)",
            "Detect Evil",
            "Detect Invisible",
            "ESP",
            "Invisibility",
            "Knock",
            "Levitate",
            "Locate Object",
            "Mirror Image",
            "Phantasmal Force",
            "Web",
            "Wizard Lock"
        ],
        "3": [
            "Clairvoyance",
            "Dispel Magic",
            "Fire Ball",
            "Fly",
            "Haste",
            "Hold Person",
            "Infravision",
            "Invisibility 10’ Radius",
            "Lightning Bolt",
            "Protection from Evil 10’ Radius",
            "Protection from Normal Missiles",
            "Water Breathing"
        ],
        "4": [
            "Charm Monster",
            "Confusion",
            "Dimension Door",
            "Growth of Plants",
            "Hallucinatory Terrain",
            "Massmorph",
            "Polymorph Others",
            "Polymorph Self",
            "Remove Curse (Curse)",
            "Wall of Fire",
            "Wall of Ice",
            "Wizard Eye"
        ],
        "5": [
            "Animate Dead",
            "Cloudkill",
            "Conjure Elemental",
            "Contact Higher Plane",
            "Feeblemind",
            "Hold Monster",
            "Magic Jar",
            "Pass-Wall",
            "Telekinesis",
            "Teleport",
            "Transmute Rock to Mud (Mud to Rock)",
            "Wall of Stone"
        ],
        "6": [
            "Anti-Magic Shell",
            "Control Weather",
            "Death Spell",
            "Disintegrate",
            "Geas (Remove Geas)",
            "Invisible Stalker",
            "Lower Water",
            "Move Earth",
            "Part Water",
            "Projected Image",
            "Reincarnation",
            "Stone to Flesh (Flesh to Stone)"
        ],
    },
    "CLERIC": {
        "1": {
            "Cure Light Wounds (Cause Lt. Wounds)",
            "Detect Evil",
            "Detect Magic",
            "Light (Darkness)",
            "Protection from Evil",
            "Purify Food and Water",
            "Remove Fear (Cause Fear)",
            "Resist Cold"
        },
        "2": {
            "Bless (Blight)",
            "Find Traps",
            "Hold Person",
            "Know Alignment",
            "Resist Fire",
            "Silence 15’ Radius",
            "Snake Charm",
            "Speak with Animals"
        },
        "3": {
            "Continual Light (Continual Darkness)",
            "Cure Disease (Cause Disease)",
            "Growth of Animal",
            "Locate Object",
            "Remove Curse (Curse)",
            "Striking"
        },
        "4": {
            "Create Water",
            "Cure Serious Wounds (Cause Sr. Wounds)",
            "Neutralize Poison",
            "Protection from Evil 10’ Radius",
            "Speak with Plants",
            "Sticks to Snakes"
        },
        "5": {
            "Commune",
            "Create Food",
            "Dispel Evil",
            "Insect Plague",
            "Quest (Remove Quest)",
            "Raise Dead (Finger of Death)"
        },
    },
    "DRUID": {
        "1": {
            "Animal Friendship",
            "Detect Danger",
            "Entangle",
            "Faerie Fire",
            "Invisibility to Animals",
            "Locate Plant or Animal",
            "Moon Touched",
            "Phantom Shield",
            "Predict Weather",
            "Speak with Animals"
        },
        "2": {
            "Barkskin",
            "Create Water",
            "Cure Light Wounds (Cause Light Wounds)",
            "Heat Metal",
            "Night's Companion",
            "Obscuring Mist",
            "Poisonous Stare",
            "Produce Flame",
            "Slow Poison",
            "Warp Wood"
        },
        "3": {
            "Black Lightning",
            "Body of Eyes",
            "Call Lightning",
            "Growth of Nature",
            "Hold Animal",
            "Protection from Poison",
            "Starlight",
            "Summon Winged Steed",
            "Tree Shape",
            "Water Breathing (Air Breathing)"
        },
        "4": {
            "Cure Serious Wounds (Cause Serious Wounds)",
            "Dispel Magic",
            "Incantation of the Moon",
            "Poisonous Spittle",
            "Protection from Fire and Lightning",
            "Speak with Plants",
            "Starlight Form",
            "Summon Animals",
            "Temperature Control"
        },
        "5": {
            "Breathe Fire",
            "Commune with Nature",
            "Control Weather",
            "Maelstrom",
            "Pass Plant",
            "Protection from Plants and Animals",
            "Transmute Rock to Mud (Mud to Rock)",
            "Wall of Thorns"
        }
    },
    "ILLUSIONIST": {
        "1": {
            "Auditory Illusion",
            "Chromatic Orb",
            "Color Spray",
            "Dancing Lights",
            "Detect Illusion",
            "Glamour",
            "Hideous Laughter",
            "Hypnotism",
            "Light (Darkness)",
            "Phantasmal Force",
            "Phantom Shield",
            "Read Magic",
            "Spook",
            "Synesthesia",
            "Wall of Fog"
        },
        "2": {
            "Alter Self",
            "Blindness / Deafness",
            "Blur",
            "Detect Magic",
            "Discord",
            "False Aura",
            "Fascinate",
            "Hypnotic Pattern",
            "Improved Phantasmal Force",
            "Invisibility",
            "Magic Mouth",
            "Mirror Image",
            "Phantasmal Armor",
            "Quasimorph",
            "Whispering Wind"
        },
        "3": {
            "Blacklight",
            "Cackling Skull",
            "Dispel Illusion",
            "Fear",
            "Hallucinatory Terrain",
            "Invisibility 10’ Radius",
            "Nondetection",
            "Paralysation",
            "Phantom Steed",
            "Rope Trick",
            "Sensory Overload",
            "Spectral Force",
            "Suggestion",
            "Wraithform"
        },
        "4": {
            "Chimerical Force",
            "Confusion",
            "Dispel Magic",
            "Emotion",
            "Illusory Stamina",
            "Improved Invisibility",
            "Massmorph",
            "Minor Creation",
            "Phantasmal Killer",
            "Rainbow Pattern",
            "Shadow Monsters",
            "Solid Fog",
            "Veil of Abandonment"
        },
        "5": {
            "Chaos",
            "Demi-Shadow Monsters",
            "Illusion",
            "Looking Glass",
            "Major Creation",
            "Maze of Mirrors",
            "Mind Fog",
            "Phantasmagoria",
            "Projected Image",
            "Seeming",
            "Shadowcast",
            "Shadowy Transformation",
            "Spell Storing",
            "Time Flow",
            "Visitation"
        },
        "6": {
            "Acid Fog",
            "Dream Quest",
            "Impersonation",
            "Manifest Dream",
            "Mass Suggestion",
            "Mislead",
            "Permanent Illusion",
            "Shades",
            "Through the Looking Glass",
            "Triggered Illusion",
            "True Seeing",
            "Vision"
        },
    },
    "NECROMANCER": {
        "1": {
            "Chill Touch",
            "Command Dead",
            "Corpse Visage",
            "Decay",
            "Deathlight",
            "Detect Undead",
            "Marionette",
            "Pass Undead",
            "Protection from Evil",
            "REad MAgic",
            "Skull Speech",
            "Undead Servitor"
        },
        "2": {
            "Bone Armor",
            "Choke",
            "Death Recall",
            "Detect Magic",
            "Feign Death",
            "Paralyzing Touch",
            "Seal Tomb",
            "Skeletal Steed",
            "Skull Sight",
            "Silence 15' Radius",
            "Speak with Dead",
            "Spectral Hand"
        },
        "3": {
            "Animate Dead, Temporary",
            "Bone Staff",
            "Carrion Stench",
            "Crypt Sight",
            "Death Ward",
            "Drag from Death's Door",
            "Fear",
            "Grave Breath",
            "Hold Person",
            "Protection from Evil 10' Radius",
            "Skull Trap",
            "Vampiric Touch"
        },
        "4": {
            "Command Undead",
            "Corpse Clairvoyance",
            "Corpse Mask",
            "Curse",
            "Dispel Magic",
            "Inter",
            "Rotting Touch",
            "Reassemble",
            "Skeletal Wings",
            "Swarm Transformation",
            "Wall of Bones",
            "Wound Transference"
        },
        "5": {
            "Animate Dead",
            "Bonewrack",
            "Cloudkill",
            "Commune with Spirit",
            "Gaseous Form",
            "Guardian Spirit",
            "Hold Undead",
            "Magic Jar",
            "Spirit Vision",
            "Summon Undead",
            "Veil of Life",
            "Wall of Gloom"
        },
        "6": {
            "Bonesteel",
            "Deathlessness",
            "Death Spell",
            "Doomveil",
            "Energy Drain",
            "Eternal Quest",
            "Necrotic Gaze",
            "Protection from Undead",
            "Sacrificial Resurrection",
            "Skeletal Army",
            "Spirit Shield",
            "Undead Regeneration"
        }
    }
}

BRAHMEL_SAYS_LIST_EXCLAIM = [
    "Aha! ",
    "Glorious! ",
    "Wonderful! ",
    "Truly exquisite! ",
    "Blessed be my ever-expanding mind! ",
    "Oh Brahmel, you've done it again! ",
]

BRAHMEL_SAYS_LIST_STATE = [
    "I've crafted a potion! ",
    "Another masterpiece! ",
    "I've created a tincture fit for kings! ",
    "Another concoction for the record books! ",
    "I've done it again! ",
    "Dr. Lumos is sure to fund such a serum! "
]

PHOTOS = [
    "more alchemical reagent please.png",
    "more blood please.png"
]

IDS = [
    142090905338380288,  #R
    119259008623181824,  #B
    337623168988610560,  #S
    744600396659425441  #C
]

SHITPOSTS = [
    "She suck my dick til I cum",
    "She W my dog til I wither",
    "She baby on my gronk til I Livvy. Then? I'm dun.",
    "She epic my gamer til I have a moment",
    "She Bobbin on my Johnny til I Steve",
    "Call her Sloppenheimer the way I get this bomb head",
    "She Jeanne my D' til I Arc",
    "She wrap my spotify til I .com",
    "She sprint on my engineer til I scrum",
    "She sunny my D til I juice",
    "She chimi my churi til I sauce",
    "Ronexiaz has been a social experiment conducted by Harvard's Department of Deep Learning and Modal Language Models. Thank you for participating.",
    "You know why they aren't called Discord \"Posts?\" It's because I'm sending messages. Everything I send is prophetic and says something about your inner being.",
    "If there was more time in the day I'd spend All of it lookin g at lamb phaal recipes",
    "She blitz my nexus til I'm filled with joy",
    "she grip my death til I AUUUUUUGGGGHHHHHHH",
    "she m my w til I 3",
    "im like seal team 6 but for tweeting",
    "new mw3 trailer feels like a crippled horse rolling down a hill on its way to a river",
    "has CHOMO ever been the wordle",
    "She Robin my Dark Knight til it Rises",
    "She clam my chicken til I chowder",
    "if they outlawed the pumpkin cream cold brew i would look like both of the tren twins combined but here we are",
    "She discover my alien til my DNA is claimed",
    "She scrooge on my blockchain til I'm Goofy",
    "part of being a complete moron is buying a whiteboard once every few years and never using it",
    "Don Draper drunkingly leaving work at noon and wandering into a Magic rhe Gathering tourney in a cafe, lighting a cigarette and whispering to some guy in shorts asking what’s happening.",
    "These are the days I wish a ho could get cold. Sadly, I'm serving giga-cunt on campus, so I must die of heat stroke.",
    "*laying in bed while the door slams*",
    "Alexa. Remove Weird Al Yankovic's Drive Thru from my Sex Playlist on Spotify.",
    "Like a child clearing away dirt and rocks in an emerald mine, I tweet.",
    "She move my castle til I Howl",
    "iSpy ft. Lil Yachty - Kyle, Verse 2 Line 2",
    "Who up gracing they dark soul?",
    "She chrome on my slugs til I harmony",
    "She N on my R til I G",
    "Who up clashin they ARAM?",
    "She chinese algae eater on my mucusy membrane til she's nourished.",
    "Call my girly The Sneeze cause her gazoon tight",
    "you ever use up all the good coffee mugs and they're just chilling in the dishwasher but you didn't run it yet so now you gotta use the WEIRD mugs?! the ones that like aren't your favorite and are shoved way back in there?! haha hope you all have a blessed morning #mugtweets",
    "Woah, guys! Haha, watch out!!! Oh boy! Ohh fuck, I'm gonna X!",
    "She tug my balls one by one til a hollow popping sound is heard. This opens the entrance to the cave.",
    "She League on my Legends til I have fun :)",
    "She dementia on my... ummm... huh?",
    "She gloomy on my galleon",
    "she D on my K til I 64",
    "She swab me lower deck til I ahoy matey!",
    "Ella me chupa el pene hasta que me corro",
    "She habla on my espanol til I bibliotecha",
    "She mustard on tha beat | She slobber on my meat | A jack-of-all-trades! | A master of skeet",
    "She meowdy on my pardner til I kitty up",
    "She light me up til my fire work",
    "She fry for four minutes on ea h side until golden brown @LockheedMartin",
    "She pork my loin til I'm tender",
    "She face me in gladiatorial combat  til I'm granted a warriors death",
    "She pad on my see til I iew",
    "Doja Cat could kill me",
    "Chi squink om ny glomble tin E gloob",
    "She toss around my pigskin til I bl-.... Dad?",
    "She eat my bad meat til I give her salmonella",
    "She single stroke on my par til I hole in one",
    "She 1367 unread emails on my inbox til I breakdown",
    "I just checked my email. I deserve a little treat. Sensitive white boys that check their emails deserve treats, don't they?",
    "She john my wayne til I gacy",
    "She look longingly into my seascape til I find purpose",
    "She 3500 dollars on my disposable income til I RAM RANCH DIRECTOR'S CUT 4K 360° MAC VR EXPERIENCE",
    "She Moby on my dick til I experience melancholy",
    "She raise my sail on the seven seas til I scurvy",
    "She roll tanks on my square til I swear nothing happened",
    "Massacre? I hardly know her!",
    "She drop it on my whiteboy til I freak it",
    "She tickle my feet til I giggle",
    "My drafts have been leaking lately. You have 12 hours to send me a video of you griddy-ing before another toxin is released.",
    "She churn my cream til I butter",
    "She conduct a search on my premises til I 19 buried 0 found",
    "She convict me for murder til I insanity plea",
    "Somehow Tobe can make tracks with Paul Wall and Nas sound good. She spin gold on my soul til I OHHHH",
    "She just a small town girl living in my lonely world til my midnight train goes anywhere",
    "She go moist on my e til I sports",
    "She arrange my paperwork til I'm deported",
    "Call me nuts the way I ball.",
    "She haha on my yeah that's fine til I AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "Alexa. Call Jill Biden.... Jill? Hey. Yeah it's me. I know you said not to call, but, I think it's time we told Joe about us.",
    "Call shawty Lexapro the way she make me go numb 🤤🤤🤤",
    "She miss one alistar combo all game til I depression",
    "She giving on my main character energy til I mother periodt",
    "She \"fix\" my powersupply til a death occurs on the job site",
    "She I can't fucking take this anymore on my day job til I T",
    "She fart in my cubicle til I call HR",
    "Call me honey the way I bee cum",
    "She go lyrical spiritual on my individual til I experience a miracle",
    "She crunch my horse til I glue",
    "And so, the cashier at Cane's set upon me. He beat me with his hands and tore my body asunder. My limbs reached the Euphrades by nightfall, my torso in Gehenna, yet my cock remained in the deep fryer.",
    "She tip my fedora til I m'lady",
    "She Phantom on my Opera til I Am There",
    "She tikka takka on my bricka bracka til my knick knacks go pop",
    "She attach an intricate pulley system to my massive load til kinetic energy is created",
    "She Jean on my Valjean til I Javert",
    "She pull on my thread til I ragdoll",
    "A shadow government runs this account. A long-echoing hivemind of only the finest comedic relief this glorious world has to offer.",
    "She vampire on my week til I end",
    "She cream on my chicken til I win codenames",
    "She democni on ym embrace tilk i precent maxchgp",
    "She walk me plank til me sail unfurls, matey.",
    "She Guitar on my Boy til I Ghanian Coup d'etat",
    "She go Lois on my Guy til we make a Family",
    "She six on my nine til I turn five twelves into zero",
    "She bloom on my sprout til I flower",
    "She amo on my gus til I Crewmate 7 times in a row",
    "She cloud on my sync til I drop",
    "Pea (pe) nuts (nis)",
    "She George on my Washington til I Carver",
    "She give me Barack til my Obama go Hussein",
    "She go fruity on my pebbles til I Yabba Dabba Doo!",
    "She CIA on my motorcade til my head explodes",
    "she Kurt on my Cobain till i blow my fucking brains out",
    "She flex on my squad til I Gold I",
    "She chicken on my tikka til I masala",
    "Shawty my lil typewriter the way her rack pop out when I present paper",
    "She Tyler on my Blevins til I THE FUCK'D YOU SAY TO ME LITTLE SHIT? WAWAHAHAHAHA",
    "She bermuda on my triangle til I eaten by crabs",
    "She family on my guy",
    "She border on my lands til I 2",
    "She dungeon on my dragon",
    "She December 4th, 1999 on my family of four til I inmate #23472 Arizona Department of Corrections",
    "She half on my • til I alive",
    "She press on my french til I delicious cup of coffee",
    "She sus on my amogus til I Impostor",
    "She G on my P til I U",
    "She movin on my castle til I howl",
    "She to on my to til I ro",
    "She crash into my south tower til I national tragedy",
    "She Matt on my Damon til I could've stopped 9/11",
    "She Jack my blu til I sky",
    "She Magnum on my P til I",
    "She make a pull request on my python til I LGTM",
    "She jump on my Empire State til I am become a fine red mist",
    "She manage to split my atom til I am become death",
    "She beat my ass in Brawlhalla Plat Ranked 1's til I 192.178.5.72 Easton, Maryland(MD), 21601",
    "She Mac on my N til I Cheese",
    "She beef my off til I'm strogan",
    "She stroggin my beef til Im off",
    "She beefin on my strogganoff",
    "She stroggin me off til I beef",
    "She cup my noodle",
    "She Joe on my Biden til I play Minecraft with Ice Spice",
    "She break into my home til I blow a quarter-sized hole in her chest with my antique flint lock",
    "She ball on my base til I steeeerrrrrrike! You're out!",
    "She Mister on my Beast",
    "She tips on my tech til I'm Linus",
    "She your on my mom til I Dog",
    "She Epic on my Rap Battles til I'm History",
    "Penis",
    "She scaf on my fold til I ing",
    "She fire on my weewoo til I alarm",
    "She erode my mental state til I",
    "She \"Awww fuck, man\" on my Thanksgiving Turkey til I \"Guess we need to make a ham\"",
    "She com on my puter",
    "She prilosec on my O til I TC",
    "She communicate to me with respect and dignity til I find a genuine and real love that only the wonderous human mind can muster",
    "She Quagmire",
    "She Griffin on my Peter",
    "She Peter on my Griffin",
    "She mustard on tha beat",
    "She open my tourbus til I cumpose",
    "She slob on my knob til I corn on the cob",
    "I'm the best fucking volibear NA",
    "She send threats to Ted Cruz til I banned off Twitter",
    "She... She left.",
    "She CIA on my Indigenous Population until I [REDACTED]",
    "She Scooby on my Dooby til I Doo",
    "Babygirl I used to work at benihana... aha, you know what that means... I can give you an utterly disappointing experience while doing mediocre close-up magic",
    "She Gerald on my Ford til I The Pardon of Richard Nixon"
]

# ERRORS
LVL_ERROR = "Level maximum cannot be less than level minimum!"
